web: &web
  build: .
  links:
   - db
   - redis
  ports:
   - "5000:5000"
  environment:
    - TOSHI_ENV=production
    - DATABASE_URL=postgres://postgres:@db:5432/toshi_production
    - REDIS_URL=redis://redis/0
  command: bundle exec puma
blockworker:
  <<: *web
  command: bundle exec sidekiq -q blocks -c 1 -r ./config/environment.rb
  ports: []
transactionworker:
  <<: *web
  command: bundle exec sidekiq -q transactions -c 1 -r ./config/environment.rb
  ports: []
peermanager:
  <<: *web
  ports: []
  command: sh -c "bundle exec find /usr/local/bundle -type f -iname protocol.rb -exec sed -i '/size > 0 ? (string, payload = payload.unpack(/s/size/size.to_s.to_i/g' {} \; && ruby bin/peer_manager.rb"
db:
  image: "postgres:latest"
redis:
  image: "redis:latest"
